hisat2-build Acropora_austera.fa results/db/Acropora_austera
hisat2-build Acropora_cervicornis.fa results/db/Acropora_cervicornis
hisat2-build Acropora_cytherea.fa results/db/Acropora_cytherea
hisat2-build Acropora_hemprichii.fa results/db/Acropora_hemprichii
hisat2-build Acropora_intermedia.fa results/db/Acropora_intermedia
hisat2-build Acropora_loripes.fa results/db/Acropora_loripes
hisat2-build Acropora_spathulata.fa results/db/Acropora_spathulata
hisat2-build Actinia_equina.fa results/db/Actinia_equina
hisat2-build Actinia_mediterranea.fa results/db/Actinia_mediterranea
hisat2-build Actinia_tenebrosa.fa results/db/Actinia_tenebrosa
hisat2-build Anthopleura_xanthogrammica.fa results/db/Anthopleura_xanthogrammica
hisat2-build Astreopora_myriophthalma.fa results/db/Astreopora_myriophthalma
hisat2-build Aurelia_aurita_complex.fa results/db/Aurelia_aurita_complex
hisat2-build Blastomussa_wellsi.fa results/db/Blastomussa_wellsi
hisat2-build Callogorgia_gracilis.fa results/db/Callogorgia_gracilis
hisat2-build Candelabrum_cocksii.fa results/db/Candelabrum_cocksii
hisat2-build Catalaphyllia_jardinei.fa results/db/Catalaphyllia_jardinei
hisat2-build Catostylus_mosaicus.fa results/db/Catostylus_mosaicus
hisat2-build Chrysaora_quinquecirrha.fa results/db/Chrysaora_quinquecirrha
hisat2-build Colpophyllia_natans.fa results/db/Colpophyllia_natans
hisat2-build Condylactis_gigantea.fa results/db/Condylactis_gigantea
hisat2-build Cyphastrea_salae.fa results/db/Cyphastrea_salae
hisat2-build Dendrogyra_cylindrus.fa results/db/Dendrogyra_cylindrus
hisat2-build Dendronephthya_gigantea.fa results/db/Dendronephthya_gigantea
hisat2-build Dendrophyllia_cribrosa.fa results/db/Dendrophyllia_cribrosa
hisat2-build Diadumene_lineata.fa results/db/Diadumene_lineata
hisat2-build Duncanopsammia_axifuga.fa results/db/Duncanopsammia_axifuga
hisat2-build Echinopora_horrida.fa results/db/Echinopora_horrida
hisat2-build Edwardsia_elegans.fa results/db/Edwardsia_elegans
hisat2-build Eunicella_cavolini.fa results/db/Eunicella_cavolini
hisat2-build Haliclystus_octoradiatus.fa results/db/Haliclystus_octoradiatus
hisat2-build Hemicorallium_imperiale.fa results/db/Hemicorallium_imperiale
hisat2-build Henneguya_salminicola.fa results/db/Henneguya_salminicola
hisat2-build Hydra_viridissima.fa results/db/Hydra_viridissima
hisat2-build Leptogorgia_sarmentosa.fa results/db/Leptogorgia_sarmentosa
hisat2-build Madracis_auretenra.fa results/db/Madracis_auretenra
hisat2-build Madracis_senaria.fa results/db/Madracis_senaria
hisat2-build Mastigias_papua.fa results/db/Mastigias_papua
hisat2-build Meandrina_meandrites.fa results/db/Meandrina_meandrites
hisat2-build Metridium_senile.fa results/db/Metridium_senile
hisat2-build Micromussa_lordhowensis.fa results/db/Micromussa_lordhowensis
hisat2-build Millepora_alcicornis.fa results/db/Millepora_alcicornis
hisat2-build Millepora_complanata.fa results/db/Millepora_complanata
hisat2-build Millepora_dichotoma.fa results/db/Millepora_dichotoma
hisat2-build Montipora_cactus.fa results/db/Montipora_cactus
hisat2-build Montipora_efflorescens.fa results/db/Montipora_efflorescens
hisat2-build Morbakka_virulenta.fa results/db/Morbakka_virulenta
hisat2-build Muricea_muricata.fa results/db/Muricea_muricata
hisat2-build Myxobolus_honghuensis.fa results/db/Myxobolus_honghuensis
hisat2-build Myxobolus_squamalis.fa results/db/Myxobolus_squamalis
hisat2-build Nemopilema_nomurai.fa results/db/Nemopilema_nomurai
hisat2-build Oculina_arbuscula.fa results/db/Oculina_arbuscula
hisat2-build Oculina_patagonica.fa results/db/Oculina_patagonica
hisat2-build Pachyseris_speciosa.fa results/db/Pachyseris_speciosa
hisat2-build Paragorgia_papillata.fa results/db/Paragorgia_papillata
hisat2-build Pelagia_noctiluca.fa results/db/Pelagia_noctiluca
hisat2-build Platygyra_sinensis.fa results/db/Platygyra_sinensis
hisat2-build Plumapathes_pennacea.fa results/db/Plumapathes_pennacea
hisat2-build Pocillopora_acuta.fa results/db/Pocillopora_acuta
hisat2-build Pocillopora_verrucosa.fa results/db/Pocillopora_verrucosa
hisat2-build Podabacia_crustacea.fa results/db/Podabacia_crustacea
hisat2-build Porites_australiensis.fa results/db/Porites_australiensis
hisat2-build Porites_compressa.fa results/db/Porites_compressa
hisat2-build Porites_cylindrica.fa results/db/Porites_cylindrica
hisat2-build Porites_divaricata.fa results/db/Porites_divaricata
hisat2-build Porites_rus.fa results/db/Porites_rus
hisat2-build Pteroeides_griseum.fa results/db/Pteroeides_griseum
hisat2-build Rhodactis_osculifera.fa results/db/Rhodactis_osculifera
hisat2-build Ricordea_florida.fa results/db/Ricordea_florida
hisat2-build Sanderia_malayensis.fa results/db/Sanderia_malayensis
hisat2-build Scolanthus_callimorphus.fa results/db/Scolanthus_callimorphus
hisat2-build Siderastrea_radians.fa results/db/Siderastrea_radians
hisat2-build Siderastrea_siderea.fa results/db/Siderastrea_siderea
hisat2-build Stephanocoenia_intersepta.fa results/db/Stephanocoenia_intersepta
hisat2-build Telmatactis_stephensoni.fa results/db/Telmatactis_stephensoni
hisat2-build Thelohanellus_kitauei.fa results/db/Thelohanellus_kitauei
hisat2-build Tubastraea_coccinea.fa results/db/Tubastraea_coccinea
hisat2-build Turbinaria_reniformis.fa results/db/Turbinaria_reniformis
hisat2-build Turritopsis_rubra.fa results/db/Turritopsis_rubra
hisat2-build Acropora_digitifera.fa results/db/Acropora_digitifera
hisat2-build Acropora_gemmifera.fa results/db/Acropora_gemmifera
hisat2-build Acropora_hyacinthus.fa results/db/Acropora_hyacinthus
hisat2-build Acropora_millepora.fa results/db/Acropora_millepora
hisat2-build Acropora_muricata.fa results/db/Acropora_muricata
hisat2-build Acropora_palmata.fa results/db/Acropora_palmata
hisat2-build Acropora_pulchra.fa results/db/Acropora_pulchra
hisat2-build Acropora_selago.fa results/db/Acropora_selago
hisat2-build Acropora_tenuis.fa results/db/Acropora_tenuis
hisat2-build Astrangia_poculata.fa results/db/Astrangia_poculata
hisat2-build Aurelia_aurita.fa results/db/Aurelia_aurita
hisat2-build Aurelia_coerulea.fa results/db/Aurelia_coerulea
hisat2-build Clytia_hemisphaerica.fa results/db/Clytia_hemisphaerica
hisat2-build Desmophyllum_pertusum.fa results/db/Desmophyllum_pertusum
hisat2-build Eunicella_verrucosa.fa results/db/Eunicella_verrucosa
hisat2-build Exaiptasia_diaphana.fa results/db/Exaiptasia_diaphana
hisat2-build Fimbriaphyllia_ancora.fa results/db/Fimbriaphyllia_ancora
hisat2-build Galaxea_fascicularis.fa results/db/Galaxea_fascicularis
hisat2-build Heliopora_coerulea.fa results/db/Heliopora_coerulea
hisat2-build Hydra_vulgaris.fa results/db/Hydra_vulgaris
hisat2-build Hydractinia_symbiolongicarpus.fa results/db/Hydractinia_symbiolongicarpus
hisat2-build Montipora_capitata.fa results/db/Montipora_capitata
hisat2-build Montipora_capricornis.fa results/db/Montipora_capricornis
hisat2-build Montipora_foliosa.fa results/db/Montipora_foliosa
hisat2-build Nematostella_vectensis.fa results/db/Nematostella_vectensis
hisat2-build Orbicella_faveolata.fa results/db/Orbicella_faveolata
hisat2-build Orbicella_franksi.fa results/db/Orbicella_franksi
hisat2-build Paramuricea_clavata.fa results/db/Paramuricea_clavata
